### ISSUE TITLE
Documentation does not show how you install or launch.

### ISSUE THREAD

**Issue by knowpath** [Azure-Samples/azure-iot-starterkit-cli#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I cannot find anywhere that it say how you install and launch the CLI. I did manage to install PIP, and then was able to install it. At least the command window says that it was installed. But not sure how you launch it. There are videos showing the CLI in use, but they start with the CLI already running.

### Any log messages given by the failure
>

### Expected/desired behavior
>Documentation that walks you through the installation and launch of the CLI.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mtyeager** [comment]
Figured out, I think, that this is an extension to the Azure CLI, and that you have to add Paths to the environment variables for the Python Scripts folder and the Azure .net SDK

**Comment by olivierbloch** [comment]
Hi @mtyeager would you consider this issue as closeable? The readme does state that you need the Azure CLI and the Azure IoT Extension for the Az CLI with links to specific instructions for each.
I added a note about the scripts folder that needs to be in the PATH.

**Comment by mtyeager** [comment]
Hi Olivier,

The instructions are packed with jargon and acronyms, but since the Grove kit is an educational product, for people to explore and test Azure IoT, shouldn’t they be written to be understandable by people who aren’t Microsoft internal developers?

Michael

**Comment by olivierbloch** [comment]
I think this is a fair point and I'll try and free up some time to clean up and simplify the instructions soon.
Closing this issue as resovled

**Comment by mtyeager** [comment]
I guess if noone is buying the kit or trying this out, then no point in improving it.

I have to admit, once I finally got it working, I was like "what now?". I don't see any guidance to take it further. How do I make it work with the sensors that my project requires?

So I am back to looking at other approaches that have vibrant communities, with lots of samples, and enthusiastic makers who provide instant feedback...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
